package com.harshcode.currencyexchange.domain.model

import currencyexchange.shared.generated.resources.Res
import currencyexchange.shared.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource

//enum class CurrencyCode(
//    val country: String,
//    val flag: DrawableResource,
//    val fullFlag: DrawableResource,
//    val currencyName: String,
//    val symbol: String
//) {
//    AED(country = "United Arab Emirates", flag = Res.drawable.united_arab_emirates, fullFlag = Res.drawable.united_arab_emirates_, symbol = "د.إ"),
//    AFN(country = "Afghanistan", flag = Res.drawable.afghanistan, fullFlag = Res.drawable.afghanistan_, symbol = "؋"),
//    ALL(country = "Albania", flag = Res.drawable.albania, fullFlag = Res.drawable.albania_, symbol = "L"),
//    AMD(country = "Armenia", flag = Res.drawable.armenia, fullFlag = Res.drawable.armenia_, symbol = "֏"),
//    ANG(country = "Netherlands", flag = Res.drawable.netherlands, fullFlag = Res.drawable.netherlands_, symbol = "ƒ"),
//    AOA(country = "Angola", flag = Res.drawable.angola, fullFlag = Res.drawable.angola_, symbol = "Kz"),
//    ARS(country = "Argentina", flag = Res.drawable.argentina, fullFlag = Res.drawable.argentina_, symbol = "$"),
//    AUD(country = "Australia", flag = Res.drawable.australia, fullFlag = Res.drawable.australia_, symbol = "$"),
//    AZN(country = "Azerbaijan", flag = Res.drawable.azerbaijan, fullFlag = Res.drawable.azerbaijan_, symbol = "₼"),
//    BAM(country = "Bosnia and Herzegovina", flag = Res.drawable.bosnia_and_herzegovina, fullFlag = Res.drawable.bosnia_and_herzegovina_, symbol = "KM"),
//    BBD(country = "Barbados", flag = Res.drawable.barbados, fullFlag = Res.drawable.barbados_, symbol = "$"),
//    BDT(country = "Bangladesh", flag = Res.drawable.bangladesh, fullFlag = Res.drawable.bangladesh_, symbol = "৳"),
//    BGN(country = "Bulgaria", flag = Res.drawable.bulgaria, fullFlag = Res.drawable.bulgaria_, symbol = "лв"),
//    BHD(country = "Bahrain", flag = Res.drawable.bahrain, fullFlag = Res.drawable.bahrain_, symbol = ".د.ب"),
//    BMD(country = "Bermuda", flag = Res.drawable.bermuda, fullFlag = Res.drawable.bermuda_, symbol = "$"),
//    BOB(country = "Bolivia", flag = Res.drawable.bolivia, fullFlag = Res.drawable.bolivia_, symbol = "Bs."),
//    BRL(country = "Brazil", flag = Res.drawable.brazil, fullFlag = Res.drawable.brazil_, symbol = "R$"),
//    BSD(country = "Bahamas", flag = Res.drawable.bahamas, fullFlag = Res.drawable.bahamas_, symbol = "$"),
//    BTN(country = "Bhutan", flag = Res.drawable.bhutan, fullFlag = Res.drawable.bhutan_, symbol = "Nu."),
//    BWP(country = "Botswana", flag = Res.drawable.botswana, fullFlag = Res.drawable.botswana_, symbol = "P"),
//    BYN(country = "Belarus", flag = Res.drawable.belarus, fullFlag = Res.drawable.belarus_, symbol = "Br"),
//    BZD(country = "Belize", flag = Res.drawable.belize, fullFlag = Res.drawable.belize_, symbol = "BZ$"),
//    CAD(country = "Canada", flag = Res.drawable.canada, fullFlag = Res.drawable.canada_, symbol = "$"),
//    CDF(country = "Democratic Republic of Congo", flag = Res.drawable.democratic_republic_of_congo, fullFlag = Res.drawable.democratic_republic_of_congo_, symbol = "FC"),
//    CHF(country = "Switzerland", flag = Res.drawable.switzerland, fullFlag = Res.drawable.switzerland_, symbol = "CHF"),
//    CLF(country = "Chile (Unidad de Fomento)", flag = Res.drawable.chile, fullFlag = Res.drawable.chile_, symbol = "UF"),
//    CLP(country = "Chile", flag = Res.drawable.chile, fullFlag = Res.drawable.chile_, symbol = "$"),
//    CNY(country = "China", flag = Res.drawable.china, fullFlag = Res.drawable.china_, symbol = "¥"),
//    COP(country = "Colombia", flag = Res.drawable.colombia, fullFlag = Res.drawable.colombia_, symbol = "$"),
//    CRC(country = "Costa Rica", flag = Res.drawable.costa_rica, fullFlag = Res.drawable.costa_rica_, symbol = "₡"),
//    CUC(country = "Cuba (Convertible Peso)", flag = Res.drawable.cuba, fullFlag = Res.drawable.cuba_, symbol = "CUC$"),
//    CUP(country = "Cuba (Cuban Peso)", flag = Res.drawable.cuba, fullFlag = Res.drawable.cuba_, symbol = "$"),
//    CVE(country = "Cape Verde", flag = Res.drawable.cape_verde, fullFlag = Res.drawable.cape_verde_, symbol = "$"),
//    CZK(country = "Czech Republic", flag = Res.drawable.czech_republic, fullFlag = Res.drawable.czech_republic_, symbol = "Kč"),
//    DJF(country = "Djibouti", flag = Res.drawable.djibouti, fullFlag = Res.drawable.djibouti_, symbol = "Fdj"),
//    DKK(country = "Denmark", flag = Res.drawable.denmark, fullFlag = Res.drawable.denmark_, symbol = "kr"),
//    DOP(country = "Dominican Republic", flag = Res.drawable.dominican_republic, fullFlag = Res.drawable.dominican_republic_, symbol = "RD$"),
//    DZD(country = "Algeria", flag = Res.drawable.algeria, fullFlag = Res.drawable.algeria_, symbol = "دج"),
//    EGP(country = "Egypt", flag = Res.drawable.egypt, fullFlag = Res.drawable.egypt_, symbol = "£"),
//    ERN(country = "Eritrea", flag = Res.drawable.eritrea, fullFlag = Res.drawable.eritrea_, symbol = "Nfk"),
//    ETB(country = "Ethiopia", flag = Res.drawable.ethiopia, fullFlag = Res.drawable.ethiopia_, symbol = "Br"),
//    EUR(country = "European Union", flag = Res.drawable.european_union, fullFlag = Res.drawable.european_union_, symbol = "€"),
//    FJD(country = "Fiji", flag = Res.drawable.fiji, fullFlag = Res.drawable.fiji_, symbol = "$"),
//    FKP(country = "Falkland Islands", flag = Res.drawable.falkland_islands, fullFlag = Res.drawable.falkland_islands_, symbol = "£"),
//    GBP(country = "United Kingdom", flag = Res.drawable.united_kingdom, fullFlag = Res.drawable.united_kingdom_, symbol = "£"),
//    GEL(country = "Georgia", flag = Res.drawable.georgia, fullFlag = Res.drawable.georgia_, symbol = "₾"),
//    GGP(country = "Guernsey", flag = Res.drawable.guernsey, fullFlag = Res.drawable.guernsey_, symbol = "£"),
//    GHS(country = "Ghana", flag = Res.drawable.ghana, fullFlag = Res.drawable.ghana_, symbol = "₵"),
//    GIP(country = "Gibraltar", flag = Res.drawable.gibraltar, fullFlag = Res.drawable.gibraltar_, symbol = "£"),
//    GMD(country = "Gambia", flag = Res.drawable.gambia, fullFlag = Res.drawable.gambia_, symbol = "D"),
//    GNF(country = "Guinea", flag = Res.drawable.guinea, fullFlag = Res.drawable.guinea_, symbol = "FG"),
//    GTQ(country = "Guatemala", flag = Res.drawable.guatemala, fullFlag = Res.drawable.guatemala_, symbol = "Q"),
//    GYD(country = "Guyana", flag = Res.drawable.guyana, fullFlag = Res.drawable.guyana_, symbol = "$"),
//    HKD(country = "Hong Kong", flag = Res.drawable.hong_kong, fullFlag = Res.drawable.hong_kong_, symbol = "$"),
//    HNL(country = "Honduras", flag = Res.drawable.honduras, fullFlag = Res.drawable.honduras_, symbol = "L"),
//    HRK(country = "Croatia", flag = Res.drawable.croatia, fullFlag = Res.drawable.croatia_, symbol = "kn"),
//    HTG(country = "Haiti", flag = Res.drawable.haiti, fullFlag = Res.drawable.haiti_, symbol = "G"),
//    HUF(country = "Hungary", flag = Res.drawable.hungary, fullFlag = Res.drawable.hungary_, symbol = "Ft"),
//    IDR(country = "Indonesia", flag = Res.drawable.indonesia, fullFlag = Res.drawable.indonesia_, symbol = "Rp"),
//    ILS(country = "Israel", flag = Res.drawable.israel, fullFlag = Res.drawable.israel_, symbol = "₪"),
//    IMP(country = "Isle of Man", flag = Res.drawable.isle_of_man, fullFlag = Res.drawable.isle_of_man_, symbol = "£"),
//    INR(country = "India", flag = Res.drawable.india, fullFlag = Res.drawable.india_, symbol = "₹"),
//    IQD(country = "Iraq", flag = Res.drawable.iraq, fullFlag = Res.drawable.iraq_, symbol = "ع.د"),
//    IRR(country = "Iran", flag = Res.drawable.iran, fullFlag = Res.drawable.iran_, symbol = "﷼"),
//    ISK(country = "Iceland", flag = Res.drawable.iceland, fullFlag = Res.drawable.iceland_, symbol = "kr"),
//    JEP(country = "Jersey", flag = Res.drawable.jersey, fullFlag = Res.drawable.jersey_, symbol = "£"),
//    JMD(country = "Jamaica", flag = Res.drawable.jamaica, fullFlag = Res.drawable.jamaica, symbol = "J$"),
//    JOD(country = "Jordan", flag = Res.drawable.jordan, fullFlag = Res.drawable.jordan_, symbol = "د.ا"),
//    JPY(country = "Japan", flag = Res.drawable.japan, fullFlag = Res.drawable.japan_, symbol = "¥"),
//    KES(country = "Kenya", flag = Res.drawable.kenya, fullFlag = Res.drawable.kenya_, symbol = "KSh"),
//    KGS(country = "Kyrgyzstan", flag = Res.drawable.kyrgyzstan, fullFlag = Res.drawable.kyrgyzstan_, symbol = "лв"),
//    KHR(country = "Cambodia", flag = Res.drawable.cambodia, fullFlag = Res.drawable.cambodia_, symbol = "៛"),
//    KMF(country = "Comoros", flag = Res.drawable.comoros, fullFlag = Res.drawable.comoros, symbol = "CF"),
//    KPW(country = "North Korea", flag = Res.drawable.north_korea, fullFlag = Res.drawable.north_korea_, symbol = "₩"),
//    KRW(country = "South Korea", flag = Res.drawable.south_korea, fullFlag = Res.drawable.south_korea_, symbol = "₩"),
//    KWD(country = "Kuwait", flag = Res.drawable.kuwait, fullFlag = Res.drawable.kuwait_, symbol = "د.ك"),
//    KZT(country = "Kazakhstan", flag = Res.drawable.kazakhstan, fullFlag = Res.drawable.kazakhstan_, symbol = "₸"),
//    LAK(country = "Laos", flag = Res.drawable.laos, fullFlag = Res.drawable.laos_, symbol = "₭"),
//    LBP(country = "Lebanon", flag = Res.drawable.lebanon, fullFlag = Res.drawable.lebanon_, symbol = "£"),
//    LKR(country = "Sri Lanka", flag = Res.drawable.sri_lanka, fullFlag = Res.drawable.sri_lanka_, symbol = "Rs"),
//    LRD(country = "Liberia", flag = Res.drawable.liberia, fullFlag = Res.drawable.liberia_, symbol = "$"),
//    LSL(country = "Lesotho", flag = Res.drawable.lesotho, fullFlag = Res.drawable.lesotho_, symbol = "L"),
//    LTL(country = "Lithuania", flag = Res.drawable.lithuania, fullFlag = Res.drawable.lithuania_, symbol = "Lt"),
//    LYD(country = "Libya", flag = Res.drawable.libya, fullFlag = Res.drawable.libya_, symbol = "ل.د"),
//    MAD(country = "Morocco", flag = Res.drawable.morocco, fullFlag = Res.drawable.morocco_, symbol = "د.م."),
//    MDL(country = "Moldova", flag = Res.drawable.moldova, fullFlag = Res.drawable.moldova_, symbol = "L"),
//    MGA(country = "Madagascar", flag = Res.drawable.madagascar, fullFlag = Res.drawable.madagascar_, symbol = "Ar"),
//    MKD(country = "North Macedonia", flag = Res.drawable.north_macedonia, fullFlag = Res.drawable.north_macedonia_, symbol = "ден"),
//    MMK(country = "Myanmar", flag = Res.drawable.myanmar, fullFlag = Res.drawable.myanmar_, symbol = "K"),
//    MNT(country = "Mongolia", flag = Res.drawable.mongolia, fullFlag = Res.drawable.mongolia_, symbol = "₮"),
//    MOP(country = "Macao", flag = Res.drawable.macao, fullFlag = Res.drawable.macao_, symbol = "MOP$"),
//    MRO(country = "Mauritania", flag = Res.drawable.mauritania, fullFlag = Res.drawable.mauritania_, symbol = "UM"),
//    MRU(country = "Mauritius", flag = Res.drawable.mauritius, fullFlag = Res.drawable.mauritius_, symbol = "₨"),
//    MUR(country = "Mauritius", flag = Res.drawable.mauritius, fullFlag = Res.drawable.mauritius_, symbol = "₨"),
//    MVR(country = "Maldives", flag = Res.drawable.maldives, fullFlag = Res.drawable.maldives_, symbol = ".ރ"),
//    MWK(country = "Malawi", flag = Res.drawable.malawi, fullFlag = Res.drawable.malawi_, symbol = "MK"),
//    MXN(country = "Mexico", flag = Res.drawable.mexico, fullFlag = Res.drawable.mexico_, symbol = "$"),
//    MYR(country = "Malaysia", flag = Res.drawable.malaysia, fullFlag = Res.drawable.malaysia_, symbol = "RM"),
//    MZN(country = "Mozambique", flag = Res.drawable.mozambique, fullFlag = Res.drawable.mozambique_, symbol = "MT"),
//    NAD(country = "Namibia", flag = Res.drawable.namibia, fullFlag = Res.drawable.namibia_, symbol = "$"),
//    NGN(country = "Nigeria", flag = Res.drawable.nigeria, fullFlag = Res.drawable.nigeria_, symbol = "₦"),
//    NIO(country = "Nicaragua", flag = Res.drawable.nicaragua, fullFlag = Res.drawable.nicaragua_, symbol = "C$"),
//    NOK(country = "Norway", flag = Res.drawable.norway, fullFlag = Res.drawable.norway_, symbol = "kr"),
//    NPR(country = "Nepal", flag = Res.drawable.nepal, fullFlag = Res.drawable.nepal_, symbol = "Rs"),
//    NZD(country = "New Zealand", flag = Res.drawable.new_zealand, fullFlag = Res.drawable.new_zealand_, symbol = "$"),
//    OMR(country = "Oman", flag = Res.drawable.oman, fullFlag = Res.drawable.oman_, symbol = "﷼"),
//    PAB(country = "Panama", flag = Res.drawable.panama, fullFlag = Res.drawable.panama_, symbol = "B/."),
//    PGK(country = "Papua New Guinea", flag = Res.drawable.papua_new_guinea, fullFlag = Res.drawable.papua_new_guinea_, symbol = "K"),
//    PHP(country = "Philippines", flag = Res.drawable.philippines, fullFlag = Res.drawable.philippines_, symbol = "₱"),
//    PKR(country = "Pakistan", flag = Res.drawable.pakistan, fullFlag = Res.drawable.pakistan_, symbol = "Rs"),
//    PLN(country = "Poland", flag = Res.drawable.poland, fullFlag = Res.drawable.poland_, symbol = "zł"),
//    PYG(country = "Paraguay", flag = Res.drawable.paraguay, fullFlag = Res.drawable.paraguay_, symbol = "Gs"),
//    QAR(country = "Qatar", flag = Res.drawable.qatar, fullFlag = Res.drawable.qatar_, symbol = "﷼"),
//    RON(country = "Romania", flag = Res.drawable.romania, fullFlag = Res.drawable.romania_, symbol = "lei"),
//    RSD(country = "Serbia", flag = Res.drawable.serbia, fullFlag = Res.drawable.serbia_, symbol = "Дин."),
//    RUB(country = "Russia", flag = Res.drawable.russia, fullFlag = Res.drawable.russia_, symbol = "₽"),
//    RWF(country = "Rwanda", flag = Res.drawable.rwanda, fullFlag = Res.drawable.rwanda_, symbol = "FRw"),
//    SAR(country = "Saudi Arabia", flag = Res.drawable.saudi_arabia, fullFlag = Res.drawable.saudi_arabia_, symbol = "﷼"),
//    SBD(country = "Solomon Islands", flag = Res.drawable.solomon_islands, fullFlag = Res.drawable.solomon_islands_, symbol = "$"),
//    SCR(country = "Seychelles", flag = Res.drawable.seychelles, fullFlag = Res.drawable.seychelles_, symbol = "₨"),
//    SDG(country = "Sudan", flag = Res.drawable.sudan, fullFlag = Res.drawable.sudan_, symbol = "ج.س."),
//    SEK(country = "Sweden", flag = Res.drawable.sweden, fullFlag = Res.drawable.sweden_, symbol = "kr"),
//    SGD(country = "Singapore", flag = Res.drawable.singapore, fullFlag = Res.drawable.singapore_, symbol = "$"),
//    SLL(country = "Sierra Leone", flag = Res.drawable.sierra_leone, fullFlag = Res.drawable.sierra_leone_, symbol = "Le"),
//    SOS(country = "Somalia", flag = Res.drawable.somalia, fullFlag = Res.drawable.somalia_, symbol = "S"),
//    SRD(country = "Suriname", flag = Res.drawable.suriname, fullFlag = Res.drawable.suriname_, symbol = "$"),
//    STD(country = "São Tomé and Príncipe", flag = Res.drawable.sao_tome_and_prince, fullFlag = Res.drawable.sao_tome_and_prince_, symbol = "Db"),
//    STN(country = "São Tomé and Príncipe", flag = Res.drawable.sao_tome_and_prince, fullFlag = Res.drawable.sao_tome_and_prince_, symbol = "Db"),
//    SVC(country = "El Salvador", flag = Res.drawable.el_salvador, fullFlag = Res.drawable.el_salvador_, symbol = "$"),
//    SYP(country = "Syria", flag = Res.drawable.syria, fullFlag = Res.drawable.syria_, symbol = "£"),
//    THB(country = "Thailand", flag = Res.drawable.thailand, fullFlag = Res.drawable.thailand_, symbol = "฿"),
//    TJS(country = "Tajikistan", flag = Res.drawable.tajikistan, fullFlag = Res.drawable.tajikistan_, symbol = "SM"),
//    TMT(country = "Turkmenistan", flag = Res.drawable.turkmenistan, fullFlag = Res.drawable.turkmenistan_, symbol = "T"),
//    TND(country = "Tunisia", flag = Res.drawable.tunisia, fullFlag = Res.drawable.tunisia_, symbol = "د.ت"),
//    TOP(country = "Tonga", flag = Res.drawable.tonga, fullFlag = Res.drawable.tonga_, symbol = "T$"),
//    TRY(country = "Turkiye", flag = Res.drawable.turkey, fullFlag = Res.drawable.turkey_, symbol = "₺"),
//    TTD(country = "Trinidad and Tobago", flag = Res.drawable.trinidad_and_tobago, fullFlag = Res.drawable.trinidad_and_tobago_, symbol = "TT$"),
//    TWD(country = "Taiwan", flag = Res.drawable.taiwan, fullFlag = Res.drawable.taiwan_, symbol = "NT$"),
//    TZS(country = "Tanzania", flag = Res.drawable.tanzania, fullFlag = Res.drawable.tanzania_, symbol = "TSh"),
//    UAH(country = "Ukraine", flag = Res.drawable.ukraine, fullFlag = Res.drawable.ukraine_, symbol = "₴"),
//    USD(country = "United States of America", flag = Res.drawable.united_states, fullFlag = Res.drawable.united_states_, symbol = "$"),
//    UZS(country = "Uzbekistan", flag = Res.drawable.uzbekista_n, fullFlag = Res.drawable.uzbekista_n_, symbol = "лв"),
//    VES(country = "Venezuela", flag = Res.drawable.venezuela, fullFlag = Res.drawable.venezuela_, symbol = "Bs.S"),
//    VND(country = "Vietnam", flag = Res.drawable.vietnam, fullFlag = Res.drawable.vietnam_, symbol = "₫"),
//    VUV(country = "Vanuatu", flag = Res.drawable.vanuatu, fullFlag = Res.drawable.vanuatu_, symbol = "VT"),
//    WST(country = "Samoa", flag = Res.drawable.samoa, fullFlag = Res.drawable.samoa_, symbol = "WS$"),
//    XAF(country = "Central African Republic", flag = Res.drawable.central_african_republic, fullFlag = Res.drawable.central_african_republic_, symbol = "FCFA"),
//    YER(country = "Yemen", flag = Res.drawable.yemen, fullFlag = Res.drawable.yemen_, symbol = "﷼"),
//    ZAR(country = "South Africa", flag = Res.drawable.south_africa, fullFlag = Res.drawable.south_africa_, symbol = "R"),
//    ZMW(country = "Zambia", flag = Res.drawable.zambia, fullFlag = Res.drawable.zambia_, symbol = "ZK"),
//    ZWL(country = "Zimbabwe", flag = Res.drawable.zimbabwe, fullFlag = Res.drawable.zimbabwe_, symbol = "$")
//}

enum class CurrencyCode(
    val country: String,
    val flag: DrawableResource,
    val fullFlag: DrawableResource,
    val currencyName: String,
    val symbol: String
) {
    AED(country = "United Arab Emirates", flag = Res.drawable.united_arab_emirates, fullFlag = Res.drawable.united_arab_emirates_, currencyName = "UAE Dirham", symbol = "د.إ"),
    AFN(country = "Afghanistan", flag = Res.drawable.afghanistan, fullFlag = Res.drawable.afghanistan_, currencyName = "Afghan Afghani", symbol = "؋"),
    ALL(country = "Albania", flag = Res.drawable.albania, fullFlag = Res.drawable.albania_, currencyName = "Albanian Lek", symbol = "L"),
    AMD(country = "Armenia", flag = Res.drawable.armenia, fullFlag = Res.drawable.armenia_, currencyName = "Armenian Dram", symbol = "֏"),
    ANG(country = "Netherlands", flag = Res.drawable.netherlands, fullFlag = Res.drawable.netherlands_, currencyName = "Netherlands Antillean Guilder", symbol = "ƒ"),
    AOA(country = "Angola", flag = Res.drawable.angola, fullFlag = Res.drawable.angola_, currencyName = "Angolan Kwanza", symbol = "Kz"),
    ARS(country = "Argentina", flag = Res.drawable.argentina, fullFlag = Res.drawable.argentina_, currencyName = "Argentine Peso", symbol = "$"),
    AUD(country = "Australia", flag = Res.drawable.australia, fullFlag = Res.drawable.australia_, currencyName = "Australian Dollar", symbol = "$"),
    AZN(country = "Azerbaijan", flag = Res.drawable.azerbaijan, fullFlag = Res.drawable.azerbaijan_, currencyName = "Azerbaijani Manat", symbol = "₼"),
    BAM(country = "Bosnia and Herzegovina", flag = Res.drawable.bosnia_and_herzegovina, fullFlag = Res.drawable.bosnia_and_herzegovina_, currencyName = "Bosnia-Herzegovina Convertible Mark", symbol = "KM"),
    BBD(country = "Barbados", flag = Res.drawable.barbados, fullFlag = Res.drawable.barbados_, currencyName = "Barbadian Dollar", symbol = "$"),
    BDT(country = "Bangladesh", flag = Res.drawable.bangladesh, fullFlag = Res.drawable.bangladesh_, currencyName = "Bangladeshi Taka", symbol = "৳"),
    BGN(country = "Bulgaria", flag = Res.drawable.bulgaria, fullFlag = Res.drawable.bulgaria_, currencyName = "Bulgarian Lev", symbol = "лв"),
    BHD(country = "Bahrain", flag = Res.drawable.bahrain, fullFlag = Res.drawable.bahrain_, currencyName = "Bahraini Dinar", symbol = ".د.ب"),
    BMD(country = "Bermuda", flag = Res.drawable.bermuda, fullFlag = Res.drawable.bermuda_, currencyName = "Bermudan Dollar", symbol = "$"),
    BOB(country = "Bolivia", flag = Res.drawable.bolivia, fullFlag = Res.drawable.bolivia_, currencyName = "Bolivian Boliviano", symbol = "Bs."),
    BRL(country = "Brazil", flag = Res.drawable.brazil, fullFlag = Res.drawable.brazil_, currencyName = "Brazilian Real", symbol = "R$"),
    BSD(country = "Bahamas", flag = Res.drawable.bahamas, fullFlag = Res.drawable.bahamas_, currencyName = "Bahamian Dollar", symbol = "$"),
    BTN(country = "Bhutan", flag = Res.drawable.bhutan, fullFlag = Res.drawable.bhutan_, currencyName = "Bhutanese Ngultrum", symbol = "Nu."),
    BWP(country = "Botswana", flag = Res.drawable.botswana, fullFlag = Res.drawable.botswana_, currencyName = "Botswanan Pula", symbol = "P"),
    BYN(country = "Belarus", flag = Res.drawable.belarus, fullFlag = Res.drawable.belarus_, currencyName = "Belarusian Ruble", symbol = "Br"),
    BZD(country = "Belize", flag = Res.drawable.belize, fullFlag = Res.drawable.belize_, currencyName = "Belize Dollar", symbol = "BZ$"),
    CAD(country = "Canada", flag = Res.drawable.canada, fullFlag = Res.drawable.canada_, currencyName = "Canadian Dollar", symbol = "$"),
    CDF(country = "Democratic Republic of Congo", flag = Res.drawable.democratic_republic_of_congo, fullFlag = Res.drawable.democratic_republic_of_congo_, currencyName = "Congolese Franc", symbol = "FC"),
    CHF(country = "Switzerland", flag = Res.drawable.switzerland, fullFlag = Res.drawable.switzerland_, currencyName = "Swiss Franc", symbol = "CHF"),
    CLF(country = "Chile (Unidad de Fomento)", flag = Res.drawable.chile, fullFlag = Res.drawable.chile_, currencyName = "Chilean Unit of Account (UF)", symbol = "UF"),
    CLP(country = "Chile", flag = Res.drawable.chile, fullFlag = Res.drawable.chile_, currencyName = "Chilean Peso", symbol = "$"),
    CNY(country = "China", flag = Res.drawable.china, fullFlag = Res.drawable.china_, currencyName = "Chinese Yuan", symbol = "¥"),
    COP(country = "Colombia", flag = Res.drawable.colombia, fullFlag = Res.drawable.colombia_, currencyName = "Colombian Peso", symbol = "$"),
    CRC(country = "Costa Rica", flag = Res.drawable.costa_rica, fullFlag = Res.drawable.costa_rica_, currencyName = "Costa Rican Colón", symbol = "₡"),
    CUC(country = "Cuba (Convertible Peso)", flag = Res.drawable.cuba, fullFlag = Res.drawable.cuba_, currencyName = "Cuban Convertible Peso", symbol = "CUC$"),
    CUP(country = "Cuba (Cuban Peso)", flag = Res.drawable.cuba, fullFlag = Res.drawable.cuba_, currencyName = "Cuban Peso", symbol = "$"),
    CVE(country = "Cape Verde", flag = Res.drawable.cape_verde, fullFlag = Res.drawable.cape_verde_, currencyName = "Cape Verdean Escudo", symbol = "$"),
    CZK(country = "Czech Republic", flag = Res.drawable.czech_republic, fullFlag = Res.drawable.czech_republic_, currencyName = "Czech Koruna", symbol = "Kč"),
    DJF(country = "Djibouti", flag = Res.drawable.djibouti, fullFlag = Res.drawable.djibouti_, currencyName = "Djiboutian Franc", symbol = "Fdj"),
    DKK(country = "Denmark", flag = Res.drawable.denmark, fullFlag = Res.drawable.denmark_, currencyName = "Danish Krone", symbol = "kr"),
    DOP(country = "Dominican Republic", flag = Res.drawable.dominican_republic, fullFlag = Res.drawable.dominican_republic_, currencyName = "Dominican Peso", symbol = "RD$"),
    DZD(country = "Algeria", flag = Res.drawable.algeria, fullFlag = Res.drawable.algeria_, currencyName = "Algerian Dinar", symbol = "دج"),
    EGP(country = "Egypt", flag = Res.drawable.egypt, fullFlag = Res.drawable.egypt_, currencyName = "Egyptian Pound", symbol = "£"),
    ERN(country = "Eritrea", flag = Res.drawable.eritrea, fullFlag = Res.drawable.eritrea_, currencyName = "Eritrean Nakfa", symbol = "Nfk"),
    ETB(country = "Ethiopia", flag = Res.drawable.ethiopia, fullFlag = Res.drawable.ethiopia_, currencyName = "Ethiopian Birr", symbol = "Br"),
    EUR(country = "European Union", flag = Res.drawable.european_union, fullFlag = Res.drawable.european_union_, currencyName = "Euro", symbol = "€"),
    FJD(country = "Fiji", flag = Res.drawable.fiji, fullFlag = Res.drawable.fiji_, currencyName = "Fijian Dollar", symbol = "$"),
    FKP(country = "Falkland Islands", flag = Res.drawable.falkland_islands, fullFlag = Res.drawable.falkland_islands_, currencyName = "Falkland Islands Pound", symbol = "£"),
    GBP(country = "United Kingdom", flag = Res.drawable.united_kingdom, fullFlag = Res.drawable.united_kingdom_, currencyName = "British Pound Sterling", symbol = "£"),
    GEL(country = "Georgia", flag = Res.drawable.georgia, fullFlag = Res.drawable.georgia_, currencyName = "Georgian Lari", symbol = "₾"),
    GGP(country = "Guernsey", flag = Res.drawable.guernsey, fullFlag = Res.drawable.guernsey_, currencyName = "Guernsey Pound", symbol = "£"),
    GHS(country = "Ghana", flag = Res.drawable.ghana, fullFlag = Res.drawable.ghana_, currencyName = "Ghanaian Cedi", symbol = "₵"),
    GIP(country = "Gibraltar", flag = Res.drawable.gibraltar, fullFlag = Res.drawable.gibraltar_, currencyName = "Gibraltar Pound", symbol = "£"),
    GMD(country = "Gambia", flag = Res.drawable.gambia, fullFlag = Res.drawable.gambia_, currencyName = "Gambian Dalasi", symbol = "D"),
    GNF(country = "Guinea", flag = Res.drawable.guinea, fullFlag = Res.drawable.guinea_, currencyName = "Guinean Franc", symbol = "FG"),
    GTQ(country = "Guatemala", flag = Res.drawable.guatemala, fullFlag = Res.drawable.guatemala_, currencyName = "Guatemalan Quetzal", symbol = "Q"),
    GYD(country = "Guyana", flag = Res.drawable.guyana, fullFlag = Res.drawable.guyana_, currencyName = "Guyanaese Dollar", symbol = "$"),
    HKD(country = "Hong Kong", flag = Res.drawable.hong_kong, fullFlag = Res.drawable.hong_kong_, currencyName = "Hong Kong Dollar", symbol = "$"),
    HNL(country = "Honduras", flag = Res.drawable.honduras, fullFlag = Res.drawable.honduras_, currencyName = "Honduran Lempira", symbol = "L"),
    HRK(country = "Croatia", flag = Res.drawable.croatia, fullFlag = Res.drawable.croatia_, currencyName = "Croatian Kuna", symbol = "kn"),
    HTG(country = "Haiti", flag = Res.drawable.haiti, fullFlag = Res.drawable.haiti_, currencyName = "Haitian Gourde", symbol = "G"),
    HUF(country = "Hungary", flag = Res.drawable.hungary, fullFlag = Res.drawable.hungary_, currencyName = "Hungarian Forint", symbol = "Ft"),
    IDR(country = "Indonesia", flag = Res.drawable.indonesia, fullFlag = Res.drawable.indonesia_, currencyName = "Indonesian Rupiah", symbol = "Rp"),
    ILS(country = "Israel", flag = Res.drawable.israel, fullFlag = Res.drawable.israel_, currencyName = "Israeli New Shekel", symbol = "₪"),
    IMP(country = "Isle of Man", flag = Res.drawable.isle_of_man, fullFlag = Res.drawable.isle_of_man_, currencyName = "Isle of Man Pound", symbol = "£"),
    INR(country = "India", flag = Res.drawable.india, fullFlag = Res.drawable.india_, currencyName = "Indian Rupee", symbol = "₹"),
    IQD(country = "Iraq", flag = Res.drawable.iraq, fullFlag = Res.drawable.iraq_, currencyName = "Iraqi Dinar", symbol = "ع.د"),
    IRR(country = "Iran", flag = Res.drawable.iran, fullFlag = Res.drawable.iran_, currencyName = "Iranian Rial", symbol = "﷼"),
    ISK(country = "Iceland", flag = Res.drawable.iceland, fullFlag = Res.drawable.iceland_, currencyName = "Icelandic Króna", symbol = "kr"),
    JEP(country = "Jersey", flag = Res.drawable.jersey, fullFlag = Res.drawable.jersey_, currencyName = "Jersey Pound", symbol = "£"),
    JMD(country = "Jamaica", flag = Res.drawable.jamaica, fullFlag = Res.drawable.jamaica, currencyName = "Jamaican Dollar", symbol = "J$"),
    JOD(country = "Jordan", flag = Res.drawable.jordan, fullFlag = Res.drawable.jordan_, currencyName = "Jordanian Dinar", symbol = "د.ا"),
    JPY(country = "Japan", flag = Res.drawable.japan, fullFlag = Res.drawable.japan_, currencyName = "Japanese Yen", symbol = "¥"),
    KES(country = "Kenya", flag = Res.drawable.kenya, fullFlag = Res.drawable.kenya_, currencyName = "Kenyan Shilling", symbol = "KSh"),
    KGS(country = "Kyrgyzstan", flag = Res.drawable.kyrgyzstan, fullFlag = Res.drawable.kyrgyzstan_, currencyName = "Kyrgystani Som", symbol = "лв"),
    KHR(country = "Cambodia", flag = Res.drawable.cambodia, fullFlag = Res.drawable.cambodia_, currencyName = "Cambodian Riel", symbol = "៛"),
    KMF(country = "Comoros", flag = Res.drawable.comoros, fullFlag = Res.drawable.comoros, currencyName = "Comorian Franc", symbol = "CF"),
    KPW(country = "North Korea", flag = Res.drawable.north_korea, fullFlag = Res.drawable.north_korea_, currencyName = "North Korean Won", symbol = "₩"),
    KRW(country = "South Korea", flag = Res.drawable.south_korea, fullFlag = Res.drawable.south_korea_, currencyName = "South Korean Won", symbol = "₩"),
    KWD(country = "Kuwait", flag = Res.drawable.kuwait, fullFlag = Res.drawable.kuwait_, currencyName = "Kuwaiti Dinar", symbol = "د.ك"),
    KZT(country = "Kazakhstan", flag = Res.drawable.kazakhstan, fullFlag = Res.drawable.kazakhstan_, currencyName = "Kazakhstani Tenge", symbol = "₸"),
    LAK(country = "Laos", flag = Res.drawable.laos, fullFlag = Res.drawable.laos_, currencyName = "Laotian Kip", symbol = "₭"),
    LBP(country = "Lebanon", flag = Res.drawable.lebanon, fullFlag = Res.drawable.lebanon_, currencyName = "Lebanese Pound", symbol = "£"),
    LKR(country = "Sri Lanka", flag = Res.drawable.sri_lanka, fullFlag = Res.drawable.sri_lanka_, currencyName = "Sri Lankan Rupee", symbol = "Rs"),
    LRD(country = "Liberia", flag = Res.drawable.liberia, fullFlag = Res.drawable.liberia_, currencyName = "Liberian Dollar", symbol = "$"),
    LSL(country = "Lesotho", flag = Res.drawable.lesotho, fullFlag = Res.drawable.lesotho_, currencyName = "Lesotho Loti", symbol = "L"),
    LTL(country = "Lithuania", flag = Res.drawable.lithuania, fullFlag = Res.drawable.lithuania_, currencyName = "Lithuanian Litas", symbol = "Lt"),
    LYD(country = "Libya", flag = Res.drawable.libya, fullFlag = Res.drawable.libya_, currencyName = "Libyan Dinar", symbol = "ل.د"),
    MAD(country = "Morocco", flag = Res.drawable.morocco, fullFlag = Res.drawable.morocco_, currencyName = "Moroccan Dirham", symbol = "د.م."),
    MDL(country = "Moldova", flag = Res.drawable.moldova, fullFlag = Res.drawable.moldova_, currencyName = "Moldovan Leu", symbol = "L"),
    MGA(country = "Madagascar", flag = Res.drawable.madagascar, fullFlag = Res.drawable.madagascar_, currencyName = "Malagasy Ariary", symbol = "Ar"),
    MKD(country = "North Macedonia", flag = Res.drawable.north_macedonia, fullFlag = Res.drawable.north_macedonia_, currencyName = "Macedonian Denar", symbol = "ден"),
    MMK(country = "Myanmar", flag = Res.drawable.myanmar, fullFlag = Res.drawable.myanmar_, currencyName = "Myanmar Kyat", symbol = "K"),
    MNT(country = "Mongolia", flag = Res.drawable.mongolia, fullFlag = Res.drawable.mongolia_, currencyName = "Mongolian Tugrik", symbol = "₮"),
    MOP(country = "Macao", flag = Res.drawable.macao, fullFlag = Res.drawable.macao_, currencyName = "Macanese Pataca", symbol = "MOP$"),
    MRO(country = "Mauritania", flag = Res.drawable.mauritania, fullFlag = Res.drawable.mauritania_, currencyName = "Mauritanian Ouguiya (pre-2018)", symbol = "UM"),
    MRU(country = "Mauritius", flag = Res.drawable.mauritius, fullFlag = Res.drawable.mauritius_, currencyName = "Mauritanian Ouguiya", symbol = "₨"),
    MUR(country = "Mauritius", flag = Res.drawable.mauritius, fullFlag = Res.drawable.mauritius_, currencyName = "Mauritian Rupee", symbol = "₨"),
    MVR(country = "Maldives", flag = Res.drawable.maldives, fullFlag = Res.drawable.maldives_, currencyName = "Maldivian Rufiyaa", symbol = ".ރ"),
    MWK(country = "Malawi", flag = Res.drawable.malawi, fullFlag = Res.drawable.malawi_, currencyName = "Malawian Kwacha", symbol = "MK"),
    MXN(country = "Mexico", flag = Res.drawable.mexico, fullFlag = Res.drawable.mexico_, currencyName = "Mexican Peso", symbol = "$"),
    MYR(country = "Malaysia", flag = Res.drawable.malaysia, fullFlag = Res.drawable.malaysia_, currencyName = "Malaysian Ringgit", symbol = "RM"),
    MZN(country = "Mozambique", flag = Res.drawable.mozambique, fullFlag = Res.drawable.mozambique_, currencyName = "Mozambican Metical", symbol = "MT"),
    NAD(country = "Namibia", flag = Res.drawable.namibia, fullFlag = Res.drawable.namibia_, currencyName = "Namibian Dollar", symbol = "$"),
    NGN(country = "Nigeria", flag = Res.drawable.nigeria, fullFlag = Res.drawable.nigeria_, currencyName = "Nigerian Naira", symbol = "₦"),
    NIO(country = "Nicaragua", flag = Res.drawable.nicaragua, fullFlag = Res.drawable.nicaragua_, currencyName = "Nicaraguan Córdoba", symbol = "C$"),
    NOK(country = "Norway", flag = Res.drawable.norway, fullFlag = Res.drawable.norway_, currencyName = "Norwegian Krone", symbol = "kr"),
    NPR(country = "Nepal", flag = Res.drawable.nepal, fullFlag = Res.drawable.nepal_, currencyName = "Nepalese Rupee", symbol = "Rs"),
    NZD(country = "New Zealand", flag = Res.drawable.new_zealand, fullFlag = Res.drawable.new_zealand_, currencyName = "New Zealand Dollar", symbol = "$"),
    OMR(country = "Oman", flag = Res.drawable.oman, fullFlag = Res.drawable.oman_, currencyName = "Omani Rial", symbol = "﷼"),
    PAB(country = "Panama", flag = Res.drawable.panama, fullFlag = Res.drawable.panama_, currencyName = "Panamanian Balboa", symbol = "B/."),
    PGK(country = "Papua New Guinea", flag = Res.drawable.papua_new_guinea, fullFlag = Res.drawable.papua_new_guinea_, currencyName = "Papua New Guinean Kina", symbol = "K"),
    PHP(country = "Philippines", flag = Res.drawable.philippines, fullFlag = Res.drawable.philippines_, currencyName = "Philippine Peso", symbol = "₱"),
    PKR(country = "Pakistan", flag = Res.drawable.pakistan, fullFlag = Res.drawable.pakistan_, currencyName = "Pakistani Rupee", symbol = "Rs"),
    PLN(country = "Poland", flag = Res.drawable.poland, fullFlag = Res.drawable.poland_, currencyName = "Polish Zloty", symbol = "zł"),
    PYG(country = "Paraguay", flag = Res.drawable.paraguay, fullFlag = Res.drawable.paraguay_, currencyName = "Paraguayan Guarani", symbol = "Gs"),
    QAR(country = "Qatar", flag = Res.drawable.qatar, fullFlag = Res.drawable.qatar_, currencyName = "Qatari Rial", symbol = "﷼"),
    RON(country = "Romania", flag = Res.drawable.romania, fullFlag = Res.drawable.romania_, currencyName = "Romanian Leu", symbol = "lei"),
    RSD(country = "Serbia", flag = Res.drawable.serbia, fullFlag = Res.drawable.serbia_, currencyName = "Serbian Dinar", symbol = "Дин."),
    RUB(country = "Russia", flag = Res.drawable.russia, fullFlag = Res.drawable.russia_, currencyName = "Russian Ruble", symbol = "₽"),
    RWF(country = "Rwanda", flag = Res.drawable.rwanda, fullFlag = Res.drawable.rwanda_, currencyName = "Rwandan Franc", symbol = "FRw"),
    SAR(country = "Saudi Arabia", flag = Res.drawable.saudi_arabia, fullFlag = Res.drawable.saudi_arabia_, currencyName = "Saudi Riyal", symbol = "﷼"),
    SBD(country = "Solomon Islands", flag = Res.drawable.solomon_islands, fullFlag = Res.drawable.solomon_islands_, currencyName = "Solomon Islands Dollar", symbol = "$"),
    SCR(country = "Seychelles", flag = Res.drawable.seychelles, fullFlag = Res.drawable.seychelles_, currencyName = "Seychellois Rupee", symbol = "₨"),
    SDG(country = "Sudan", flag = Res.drawable.sudan, fullFlag = Res.drawable.sudan_, currencyName = "Sudanese Pound", symbol = "ج.س."),
    SEK(country = "Sweden", flag = Res.drawable.sweden, fullFlag = Res.drawable.sweden_, currencyName = "Swedish Krona", symbol = "kr"),
    SGD(country = "Singapore", flag = Res.drawable.singapore, fullFlag = Res.drawable.singapore_, currencyName = "Singapore Dollar", symbol = "$"),
    SLL(country = "Sierra Leone", flag = Res.drawable.sierra_leone, fullFlag = Res.drawable.sierra_leone_, currencyName = "Sierra Leonean Leone", symbol = "Le"),
    SOS(country = "Somalia", flag = Res.drawable.somalia, fullFlag = Res.drawable.somalia_, currencyName = "Somali Shilling", symbol = "S"),
    SRD(country = "Suriname", flag = Res.drawable.suriname, fullFlag = Res.drawable.suriname_, currencyName = "Surinamese Dollar", symbol = "$"),
    STD(country = "São Tomé and Príncipe", flag = Res.drawable.sao_tome_and_prince, fullFlag = Res.drawable.sao_tome_and_prince_, currencyName = "São Tomé and Príncipe Dobra (pre-2018)", symbol = "Db"),
    STN(country = "São Tomé and Príncipe", flag = Res.drawable.sao_tome_and_prince, fullFlag = Res.drawable.sao_tome_and_prince_, currencyName = "São Tomé and Príncipe Dobra", symbol = "Db"),
    SVC(country = "El Salvador", flag = Res.drawable.el_salvador, fullFlag = Res.drawable.el_salvador_, currencyName = "Salvadoran Colón", symbol = "$"),
    SYP(country = "Syria", flag = Res.drawable.syria, fullFlag = Res.drawable.syria_, currencyName = "Syrian Pound", symbol = "£"),
    THB(country = "Thailand", flag = Res.drawable.thailand, fullFlag = Res.drawable.thailand_, currencyName = "Thai Baht", symbol = "฿"),
    TJS(country = "Tajikistan", flag = Res.drawable.tajikistan, fullFlag = Res.drawable.tajikistan_, currencyName = "Tajikistani Somoni", symbol = "SM"),
    TMT(country = "Turkmenistan", flag = Res.drawable.turkmenistan, fullFlag = Res.drawable.turkmenistan_, currencyName = "Turkmenistani Manat", symbol = "T"),
    TND(country = "Tunisia", flag = Res.drawable.tunisia, fullFlag = Res.drawable.tunisia_, currencyName = "Tunisian Dinar", symbol = "د.ت"),
    TOP(country = "Tonga", flag = Res.drawable.tonga, fullFlag = Res.drawable.tonga_, currencyName = "Tongan Pa'anga", symbol = "T$"),
    TRY(country = "Turkiye", flag = Res.drawable.turkey, fullFlag = Res.drawable.turkey_, currencyName = "Turkish Lira", symbol = "₺"),
    TTD(country = "Trinidad and Tobago", flag = Res.drawable.trinidad_and_tobago, fullFlag = Res.drawable.trinidad_and_tobago_, currencyName = "Trinidad and Tobago Dollar", symbol = "TT$"),
    TWD(country = "Taiwan", flag = Res.drawable.taiwan, fullFlag = Res.drawable.taiwan_, currencyName = "New Taiwan Dollar", symbol = "NT$"),
    TZS(country = "Tanzania", flag = Res.drawable.tanzania, fullFlag = Res.drawable.tanzania_, currencyName = "Tanzanian Shilling", symbol = "TSh"),
    UAH(country = "Ukraine", flag = Res.drawable.ukraine, fullFlag = Res.drawable.ukraine_, currencyName = "Ukrainian Hryvnia", symbol = "₴"),
    USD(country = "United States of America", flag = Res.drawable.united_states, fullFlag = Res.drawable.united_states_, currencyName = "United States Dollar", symbol = "$"),
    UZS(country = "Uzbekistan", flag = Res.drawable.uzbekista_n, fullFlag = Res.drawable.uzbekista_n_, currencyName = "Uzbekistani Som", symbol = "лв"),
    VES(country = "Venezuela", flag = Res.drawable.venezuela, fullFlag = Res.drawable.venezuela_, currencyName = "Venezuelan Bolívar Soberano", symbol = "Bs.S"),
    VND(country = "Vietnam", flag = Res.drawable.vietnam, fullFlag = Res.drawable.vietnam_, currencyName = "Vietnamese Dong", symbol = "₫"),
    VUV(country = "Vanuatu", flag = Res.drawable.vanuatu, fullFlag = Res.drawable.vanuatu_, currencyName = "Vanuatu Vatu", symbol = "VT"),
    WST(country = "Samoa", flag = Res.drawable.samoa, fullFlag = Res.drawable.samoa_, currencyName = "Samoan Tala", symbol = "WS$"),
    XAF(country = "Central African Republic", flag = Res.drawable.central_african_republic, fullFlag = Res.drawable.central_african_republic_, currencyName = "Central African CFA Franc", symbol = "FCFA"),
    YER(country = "Yemen", flag = Res.drawable.yemen, fullFlag = Res.drawable.yemen_, currencyName = "Yemeni Rial", symbol = "﷼"),
    ZAR(country = "South Africa", flag = Res.drawable.south_africa, fullFlag = Res.drawable.south_africa_, currencyName = "South African Rand", symbol = "R"),
    ZMW(country = "Zambia", flag = Res.drawable.zambia, fullFlag = Res.drawable.zambia_, currencyName = "Zambian Kwacha", symbol = "ZK"),
    ZWL(country = "Zimbabwe", flag = Res.drawable.zimbabwe, fullFlag = Res.drawable.zimbabwe_, currencyName = "Zimbabwean Dollar", symbol = "$")
}