package com.harshcode.currencyexchange.domain.model

import currencyexchange.shared.generated.resources.Res
import currencyexchange.shared.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource

enum class CurrencyCode(
    val country: String,
    val flag: DrawableResource,
    val fullFlag: DrawableResource,
    val symbol: String
) {
    AED(country = "United Arab Emirates", flag = Res.drawable.united_arab_emirates, fullFlag = Res.drawable.united_arab_emirates_, symbol = "د.إ"),
    AFN(country = "Afghanistan", flag = Res.drawable.afghanistan, fullFlag = Res.drawable.afghanistan_, symbol = "؋"),
    ALL(country = "Albania", flag = Res.drawable.albania, fullFlag = Res.drawable.albania_, symbol = "L"),
    AMD(country = "Armenia", flag = Res.drawable.armenia, fullFlag = Res.drawable.armenia_, symbol = "֏"),
    ANG(country = "Netherlands", flag = Res.drawable.netherlands, fullFlag = Res.drawable.netherlands_, symbol = "ƒ"),
    AOA(country = "Angola", flag = Res.drawable.angola, fullFlag = Res.drawable.angola_, symbol = "Kz"),
    ARS(country = "Argentina", flag = Res.drawable.argentina, fullFlag = Res.drawable.argentina_, symbol = "$"),
    AUD(country = "Australia", flag = Res.drawable.australia, fullFlag = Res.drawable.australia_, symbol = "$"),
    AZN(country = "Azerbaijan", flag = Res.drawable.azerbaijan, fullFlag = Res.drawable.azerbaijan_, symbol = "₼"),
    BAM(country = "Bosnia and Herzegovina", flag = Res.drawable.bosnia_and_herzegovina, fullFlag = Res.drawable.bosnia_and_herzegovina_, symbol = "KM"),
    BBD(country = "Barbados", flag = Res.drawable.barbados, fullFlag = Res.drawable.barbados_, symbol = "$"),
    BDT(country = "Bangladesh", flag = Res.drawable.bangladesh, fullFlag = Res.drawable.bangladesh_, symbol = "৳"),
    BGN(country = "Bulgaria", flag = Res.drawable.bulgaria, fullFlag = Res.drawable.bulgaria_, symbol = "лв"),
    BHD(country = "Bahrain", flag = Res.drawable.bahrain, fullFlag = Res.drawable.bahrain_, symbol = ".د.ب"),
    BMD(country = "Bermuda", flag = Res.drawable.bermuda, fullFlag = Res.drawable.bermuda_, symbol = "$"),
    BOB(country = "Bolivia", flag = Res.drawable.bolivia, fullFlag = Res.drawable.bolivia_, symbol = "Bs."),
    BRL(country = "Brazil", flag = Res.drawable.brazil, fullFlag = Res.drawable.brazil_, symbol = "R$"),
    BSD(country = "Bahamas", flag = Res.drawable.bahamas, fullFlag = Res.drawable.bahamas_, symbol = "$"),
    BTN(country = "Bhutan", flag = Res.drawable.bhutan, fullFlag = Res.drawable.bhutan_, symbol = "Nu."),
    BWP(country = "Botswana", flag = Res.drawable.botswana, fullFlag = Res.drawable.botswana_, symbol = "P"),
    BYN(country = "Belarus", flag = Res.drawable.belarus, fullFlag = Res.drawable.belarus_, symbol = "Br"),
    BZD(country = "Belize", flag = Res.drawable.belize, fullFlag = Res.drawable.belize_, symbol = "BZ$"),
    CAD(country = "Canada", flag = Res.drawable.canada, fullFlag = Res.drawable.canada_, symbol = "$"),
    CDF(country = "Democratic Republic of Congo", flag = Res.drawable.democratic_republic_of_congo, fullFlag = Res.drawable.democratic_republic_of_congo_, symbol = "FC"),
    CHF(country = "Switzerland", flag = Res.drawable.switzerland, fullFlag = Res.drawable.switzerland_, symbol = "CHF"),
    CLF(country = "Chile (Unidad de Fomento)", flag = Res.drawable.chile, fullFlag = Res.drawable.chile_, symbol = "UF"),
    CLP(country = "Chile", flag = Res.drawable.chile, fullFlag = Res.drawable.chile_, symbol = "$"),
    CNY(country = "China", flag = Res.drawable.china, fullFlag = Res.drawable.china_, symbol = "¥"),
    COP(country = "Colombia", flag = Res.drawable.colombia, fullFlag = Res.drawable.colombia_, symbol = "$"),
    CRC(country = "Costa Rica", flag = Res.drawable.costa_rica, fullFlag = Res.drawable.costa_rica_, symbol = "₡"),
    CUC(country = "Cuba (Convertible Peso)", flag = Res.drawable.cuba, fullFlag = Res.drawable.cuba_, symbol = "CUC$"),
    CUP(country = "Cuba (Cuban Peso)", flag = Res.drawable.cuba, fullFlag = Res.drawable.cuba_, symbol = "$"),
    CVE(country = "Cape Verde", flag = Res.drawable.cape_verde, fullFlag = Res.drawable.cape_verde_, symbol = "$"),
    CZK(country = "Czech Republic", flag = Res.drawable.czech_republic, fullFlag = Res.drawable.czech_republic_, symbol = "Kč"),
    DJF(country = "Djibouti", flag = Res.drawable.djibouti, fullFlag = Res.drawable.djibouti_, symbol = "Fdj"),
    DKK(country = "Denmark", flag = Res.drawable.denmark, fullFlag = Res.drawable.denmark_, symbol = "kr"),
    DOP(country = "Dominican Republic", flag = Res.drawable.dominican_republic, fullFlag = Res.drawable.dominican_republic_, symbol = "RD$"),
    DZD(country = "Algeria", flag = Res.drawable.algeria, fullFlag = Res.drawable.algeria_, symbol = "دج"),
    EGP(country = "Egypt", flag = Res.drawable.egypt, fullFlag = Res.drawable.egypt_, symbol = "£"),
    ERN(country = "Eritrea", flag = Res.drawable.eritrea, fullFlag = Res.drawable.eritrea_, symbol = "Nfk"),
    ETB(country = "Ethiopia", flag = Res.drawable.ethiopia, fullFlag = Res.drawable.ethiopia_, symbol = "Br"),
    EUR(country = "European Union", flag = Res.drawable.european_union, fullFlag = Res.drawable.european_union_, symbol = "€"),
    FJD(country = "Fiji", flag = Res.drawable.fiji, fullFlag = Res.drawable.fiji_, symbol = "$"),
    FKP(country = "Falkland Islands", flag = Res.drawable.falkland_islands, fullFlag = Res.drawable.falkland_islands_, symbol = "£"),
    GBP(country = "United Kingdom", flag = Res.drawable.united_kingdom, fullFlag = Res.drawable.united_kingdom_, symbol = "£"),
    GEL(country = "Georgia", flag = Res.drawable.georgia, fullFlag = Res.drawable.georgia_, symbol = "₾"),
    GGP(country = "Guernsey", flag = Res.drawable.guernsey, fullFlag = Res.drawable.guernsey_, symbol = "£"),
    GHS(country = "Ghana", flag = Res.drawable.ghana, fullFlag = Res.drawable.ghana_, symbol = "₵"),
    GIP(country = "Gibraltar", flag = Res.drawable.gibraltar, fullFlag = Res.drawable.gibraltar_, symbol = "£"),
    GMD(country = "Gambia", flag = Res.drawable.gambia, fullFlag = Res.drawable.gambia_, symbol = "D"),
    GNF(country = "Guinea", flag = Res.drawable.guinea, fullFlag = Res.drawable.guinea_, symbol = "FG"),
    GTQ(country = "Guatemala", flag = Res.drawable.guatemala, fullFlag = Res.drawable.guatemala_, symbol = "Q"),
    GYD(country = "Guyana", flag = Res.drawable.guyana, fullFlag = Res.drawable.guyana_, symbol = "$"),
    HKD(country = "Hong Kong", flag = Res.drawable.hong_kong, fullFlag = Res.drawable.hong_kong_, symbol = "$"),
    HNL(country = "Honduras", flag = Res.drawable.honduras, fullFlag = Res.drawable.honduras_, symbol = "L"),
    HRK(country = "Croatia", flag = Res.drawable.croatia, fullFlag = Res.drawable.croatia_, symbol = "kn"),
    HTG(country = "Haiti", flag = Res.drawable.haiti, fullFlag = Res.drawable.haiti_, symbol = "G"),
    HUF(country = "Hungary", flag = Res.drawable.hungary, fullFlag = Res.drawable.hungary_, symbol = "Ft"),
    IDR(country = "Indonesia", flag = Res.drawable.indonesia, fullFlag = Res.drawable.indonesia_, symbol = "Rp"),
    ILS(country = "Israel", flag = Res.drawable.israel, fullFlag = Res.drawable.israel_, symbol = "₪"),
    IMP(country = "Isle of Man", flag = Res.drawable.isle_of_man, fullFlag = Res.drawable.isle_of_man_, symbol = "£"),
    INR(country = "India", flag = Res.drawable.india, fullFlag = Res.drawable.india_, symbol = "₹"),
    IQD(country = "Iraq", flag = Res.drawable.iraq, fullFlag = Res.drawable.iraq_, symbol = "ع.د"),
    IRR(country = "Iran", flag = Res.drawable.iran, fullFlag = Res.drawable.iran_, symbol = "﷼"),
    ISK(country = "Iceland", flag = Res.drawable.iceland, fullFlag = Res.drawable.iceland_, symbol = "kr"),
    JEP(country = "Jersey", flag = Res.drawable.jersey, fullFlag = Res.drawable.jersey_, symbol = "£"),
    JMD(country = "Jamaica", flag = Res.drawable.jamaica, fullFlag = Res.drawable.jamaica, symbol = "J$"),
    JOD(country = "Jordan", flag = Res.drawable.jordan, fullFlag = Res.drawable.jordan_, symbol = "د.ا"),
    JPY(country = "Japan", flag = Res.drawable.japan, fullFlag = Res.drawable.japan_, symbol = "¥"),
    KES(country = "Kenya", flag = Res.drawable.kenya, fullFlag = Res.drawable.kenya_, symbol = "KSh"),
    KGS(country = "Kyrgyzstan", flag = Res.drawable.kyrgyzstan, fullFlag = Res.drawable.kyrgyzstan_, symbol = "лв"),
    KHR(country = "Cambodia", flag = Res.drawable.cambodia, fullFlag = Res.drawable.cambodia_, symbol = "៛"),
    KMF(country = "Comoros", flag = Res.drawable.comoros, fullFlag = Res.drawable.comoros, symbol = "CF"),
    KPW(country = "North Korea", flag = Res.drawable.north_korea, fullFlag = Res.drawable.north_korea_, symbol = "₩"),
    KRW(country = "South Korea", flag = Res.drawable.south_korea, fullFlag = Res.drawable.south_korea_, symbol = "₩"),
    KWD(country = "Kuwait", flag = Res.drawable.kuwait, fullFlag = Res.drawable.kuwait_, symbol = "د.ك"),
    KZT(country = "Kazakhstan", flag = Res.drawable.kazakhstan, fullFlag = Res.drawable.kazakhstan_, symbol = "₸"),
    LAK(country = "Laos", flag = Res.drawable.laos, fullFlag = Res.drawable.laos_, symbol = "₭"),
    LBP(country = "Lebanon", flag = Res.drawable.lebanon, fullFlag = Res.drawable.lebanon_, symbol = "£"),
    LKR(country = "Sri Lanka", flag = Res.drawable.sri_lanka, fullFlag = Res.drawable.sri_lanka_, symbol = "Rs"),
    LRD(country = "Liberia", flag = Res.drawable.liberia, fullFlag = Res.drawable.liberia_, symbol = "$"),
    LSL(country = "Lesotho", flag = Res.drawable.lesotho, fullFlag = Res.drawable.lesotho_, symbol = "L"),
    LTL(country = "Lithuania", flag = Res.drawable.lithuania, fullFlag = Res.drawable.lithuania_, symbol = "Lt"),
    LYD(country = "Libya", flag = Res.drawable.libya, fullFlag = Res.drawable.libya_, symbol = "ل.د"),
    MAD(country = "Morocco", flag = Res.drawable.morocco, fullFlag = Res.drawable.morocco_, symbol = "د.م."),
    MDL(country = "Moldova", flag = Res.drawable.moldova, fullFlag = Res.drawable.moldova_, symbol = "L"),
    MGA(country = "Madagascar", flag = Res.drawable.madagascar, fullFlag = Res.drawable.madagascar_, symbol = "Ar"),
    MKD(country = "North Macedonia", flag = Res.drawable.north_macedonia, fullFlag = Res.drawable.north_macedonia_, symbol = "ден"),
    MMK(country = "Myanmar", flag = Res.drawable.myanmar, fullFlag = Res.drawable.myanmar_, symbol = "K"),
    MNT(country = "Mongolia", flag = Res.drawable.mongolia, fullFlag = Res.drawable.mongolia_, symbol = "₮"),
    MOP(country = "Macao", flag = Res.drawable.macao, fullFlag = Res.drawable.macao_, symbol = "MOP$"),
    MRO(country = "Mauritania", flag = Res.drawable.mauritania, fullFlag = Res.drawable.mauritania_, symbol = "UM"),
    MRU(country = "Mauritius", flag = Res.drawable.mauritius, fullFlag = Res.drawable.mauritius_, symbol = "₨"),
    MUR(country = "Mauritius", flag = Res.drawable.mauritius, fullFlag = Res.drawable.mauritius_, symbol = "₨"),
    MVR(country = "Maldives", flag = Res.drawable.maldives, fullFlag = Res.drawable.maldives_, symbol = ".ރ"),
    MWK(country = "Malawi", flag = Res.drawable.malawi, fullFlag = Res.drawable.malawi_, symbol = "MK"),
    MXN(country = "Mexico", flag = Res.drawable.mexico, fullFlag = Res.drawable.mexico_, symbol = "$"),
    MYR(country = "Malaysia", flag = Res.drawable.malaysia, fullFlag = Res.drawable.malaysia_, symbol = "RM"),
    MZN(country = "Mozambique", flag = Res.drawable.mozambique, fullFlag = Res.drawable.mozambique_, symbol = "MT"),
    NAD(country = "Namibia", flag = Res.drawable.namibia, fullFlag = Res.drawable.namibia_, symbol = "$"),
    NGN(country = "Nigeria", flag = Res.drawable.nigeria, fullFlag = Res.drawable.nigeria_, symbol = "₦"),
    NIO(country = "Nicaragua", flag = Res.drawable.nicaragua, fullFlag = Res.drawable.nicaragua_, symbol = "C$"),
    NOK(country = "Norway", flag = Res.drawable.norway, fullFlag = Res.drawable.norway_, symbol = "kr"),
    NPR(country = "Nepal", flag = Res.drawable.nepal, fullFlag = Res.drawable.nepal_, symbol = "Rs"),
    NZD(country = "New Zealand", flag = Res.drawable.new_zealand, fullFlag = Res.drawable.new_zealand_, symbol = "$"),
    OMR(country = "Oman", flag = Res.drawable.oman, fullFlag = Res.drawable.oman_, symbol = "﷼"),
    PAB(country = "Panama", flag = Res.drawable.panama, fullFlag = Res.drawable.panama_, symbol = "B/."),
    PGK(country = "Papua New Guinea", flag = Res.drawable.papua_new_guinea, fullFlag = Res.drawable.papua_new_guinea_, symbol = "K"),
    PHP(country = "Philippines", flag = Res.drawable.philippines, fullFlag = Res.drawable.philippines_, symbol = "₱"),
    PKR(country = "Pakistan", flag = Res.drawable.pakistan, fullFlag = Res.drawable.pakistan_, symbol = "Rs"),
    PLN(country = "Poland", flag = Res.drawable.poland, fullFlag = Res.drawable.poland_, symbol = "zł"),
    PYG(country = "Paraguay", flag = Res.drawable.paraguay, fullFlag = Res.drawable.paraguay_, symbol = "Gs"),
    QAR(country = "Qatar", flag = Res.drawable.qatar, fullFlag = Res.drawable.qatar_, symbol = "﷼"),
    RON(country = "Romania", flag = Res.drawable.romania, fullFlag = Res.drawable.romania_, symbol = "lei"),
    RSD(country = "Serbia", flag = Res.drawable.serbia, fullFlag = Res.drawable.serbia_, symbol = "Дин."),
    RUB(country = "Russia", flag = Res.drawable.russia, fullFlag = Res.drawable.russia_, symbol = "₽"),
    RWF(country = "Rwanda", flag = Res.drawable.rwanda, fullFlag = Res.drawable.rwanda_, symbol = "FRw"),
    SAR(country = "Saudi Arabia", flag = Res.drawable.saudi_arabia, fullFlag = Res.drawable.saudi_arabia_, symbol = "﷼"),
    SBD(country = "Solomon Islands", flag = Res.drawable.solomon_islands, fullFlag = Res.drawable.solomon_islands_, symbol = "$"),
    SCR(country = "Seychelles", flag = Res.drawable.seychelles, fullFlag = Res.drawable.seychelles_, symbol = "₨"),
    SDG(country = "Sudan", flag = Res.drawable.sudan, fullFlag = Res.drawable.sudan_, symbol = "ج.س."),
    SEK(country = "Sweden", flag = Res.drawable.sweden, fullFlag = Res.drawable.sweden_, symbol = "kr"),
    SGD(country = "Singapore", flag = Res.drawable.singapore, fullFlag = Res.drawable.singapore_, symbol = "$"),
    SLL(country = "Sierra Leone", flag = Res.drawable.sierra_leone, fullFlag = Res.drawable.sierra_leone_, symbol = "Le"),
    SOS(country = "Somalia", flag = Res.drawable.somalia, fullFlag = Res.drawable.somalia_, symbol = "S"),
    SRD(country = "Suriname", flag = Res.drawable.suriname, fullFlag = Res.drawable.suriname_, symbol = "$"),
    STD(country = "São Tomé and Príncipe", flag = Res.drawable.sao_tome_and_prince, fullFlag = Res.drawable.sao_tome_and_prince_, symbol = "Db"),
    STN(country = "São Tomé and Príncipe", flag = Res.drawable.sao_tome_and_prince, fullFlag = Res.drawable.sao_tome_and_prince_, symbol = "Db"),
    SVC(country = "El Salvador", flag = Res.drawable.el_salvador, fullFlag = Res.drawable.el_salvador_, symbol = "$"),
    SYP(country = "Syria", flag = Res.drawable.syria, fullFlag = Res.drawable.syria_, symbol = "£"),
    THB(country = "Thailand", flag = Res.drawable.thailand, fullFlag = Res.drawable.thailand_, symbol = "฿"),
    TJS(country = "Tajikistan", flag = Res.drawable.tajikistan, fullFlag = Res.drawable.tajikistan_, symbol = "SM"),
    TMT(country = "Turkmenistan", flag = Res.drawable.turkmenistan, fullFlag = Res.drawable.turkmenistan_, symbol = "T"),
    TND(country = "Tunisia", flag = Res.drawable.tunisia, fullFlag = Res.drawable.tunisia_, symbol = "د.ت"),
    TOP(country = "Tonga", flag = Res.drawable.tonga, fullFlag = Res.drawable.tonga_, symbol = "T$"),
    TRY(country = "Turkiye", flag = Res.drawable.turkey, fullFlag = Res.drawable.turkey_, symbol = "₺"),
    TTD(country = "Trinidad and Tobago", flag = Res.drawable.trinidad_and_tobago, fullFlag = Res.drawable.trinidad_and_tobago_, symbol = "TT$"),
    TWD(country = "Taiwan", flag = Res.drawable.taiwan, fullFlag = Res.drawable.taiwan_, symbol = "NT$"),
    TZS(country = "Tanzania", flag = Res.drawable.tanzania, fullFlag = Res.drawable.tanzania_, symbol = "TSh"),
    UAH(country = "Ukraine", flag = Res.drawable.ukraine, fullFlag = Res.drawable.ukraine_, symbol = "₴"),
    USD(country = "United States of America", flag = Res.drawable.united_states, fullFlag = Res.drawable.united_states_, symbol = "$"),
    UZS(country = "Uzbekistan", flag = Res.drawable.uzbekista_n, fullFlag = Res.drawable.uzbekista_n_, symbol = "лв"),
    VES(country = "Venezuela", flag = Res.drawable.venezuela, fullFlag = Res.drawable.venezuela_, symbol = "Bs.S"),
    VND(country = "Vietnam", flag = Res.drawable.vietnam, fullFlag = Res.drawable.vietnam_, symbol = "₫"),
    VUV(country = "Vanuatu", flag = Res.drawable.vanuatu, fullFlag = Res.drawable.vanuatu_, symbol = "VT"),
    WST(country = "Samoa", flag = Res.drawable.samoa, fullFlag = Res.drawable.samoa_, symbol = "WS$"),
    XAF(country = "Central African Republic", flag = Res.drawable.central_african_republic, fullFlag = Res.drawable.central_african_republic_, symbol = "FCFA"),
    YER(country = "Yemen", flag = Res.drawable.yemen, fullFlag = Res.drawable.yemen_, symbol = "﷼"),
    ZAR(country = "South Africa", flag = Res.drawable.south_africa, fullFlag = Res.drawable.south_africa_, symbol = "R"),
    ZMW(country = "Zambia", flag = Res.drawable.zambia, fullFlag = Res.drawable.zambia_, symbol = "ZK"),
    ZWL(country = "Zimbabwe", flag = Res.drawable.zimbabwe, fullFlag = Res.drawable.zimbabwe_, symbol = "$")
}
